export const EVENT_TYPES: Record<string, string[]> = {
  "Engineering & Technology": [
    "hackathon",
    "certification", 
    "scholarship",
    "bootcamp",
    "tech fest",
    "government programs",
  ],
  "Education & Research": [
    "conference",
    "webinar", 
    "research paper competition",
    "forum",
    "scholarship",
    "research",
    "certification",
    "research collaboration",
    "research funding",
    "government programs",
  ],
  "Business & Finance": [
    "certification",
    "webinar",
    "scholarship", 
    "bootcamp",
    "workshop",
    "community",
    "government programs",
  ],
  "Arts & Design": [
    "conference",
    "webinar",
    "competition",
    "forum", 
    "certification",
    "community",
    "ui/ux competition",
    "scholarship",
    "government programs",
  ],
  "Culinary & Hospitality": [
    "institutes",
    "webinar",
    "competition",
    "forum",
    "scholarship",
    "certification", 
    "bootcamp",
    "government programs",
  ],
  "Medical/Healthcare": [
    "scholarship",
    "conference",
    "webinar",
    "certification",
    "forum",
    "volunteering",
    "fest",
    "government programs",
  ],
  "Law & Public Service": [
    "conference", 
    "webinar",
    "volunteering",
    "forum",
    "government programs",
    "scholarship",
    "community",
  ],
  "Sports & Fitness": [
    "certification",
    "tournaments",
    "programs",
    "forum",
    "trails",
    "scholarship", 
    "government programs",
  ],
  
  // ADD THESE MISSING CATEGORIES:
  "Entertainment & Media": [
    "competition",
    "audition",
    "festival", 
    "workshop",
    "certification",
    "networking",
    "scholarship",
    "government programs",
  ],
  "Science & Environment": [
    "conference",
    "research",
    "scholarship",
    "certification",
    "webinar",
    "research collaboration",
    "research funding",
    "government programs",
  ],
  "Others": [
    "scholarship",
    "workshop", 
    "webinar",
    "opportunity",
    "certification",
    "government programs",
    "networking",
    "competition",
  ],
  
  default: [
    "scholarship", 
    "workshop",
    "webinar", 
    "opportunity",
    "trails",
    "hackathon",
    "government programs",
    "certification",
    "volunteering",
    "bootcamp",
    "research paper competition"
  ],
};
