// utils/eventSitesByType.ts

export const EVENT_SITES_BY_TYPE: Record<string, string[]> = {
    hackathon: [
      "devpost.com/hackathons",
      "vision.hack2skill.com/hackathons-listing",
      "hackerearth.com/challenges/hackathon",
      "unstop.com/hackathons",
      "devfolio.co/hackathons",
      "mlh.io/seasons/2025/events",
      "hackathons.hackclub.com",
      "hackalist.org",
      "hackathon.com",
      "reskilll.com/allhacks",
    ],
    certification: [
      "coursera.org",
      "edx.org",
      "udemy.com",
      "linkedin.com/learning",
      "udacity.com",
      "aws.amazon.com/training",
      "grow.google/certificates",
      "skillshare.com",
      "nptel.ac.in",
      "dth.ac.in/medical/national.php",
      "swayam.gov.in/explorer?category=Health_Sciences",
    ],
    scholarship: [
      "springboard.com/how-it-works/scholarships",
      "codingdojo.com/grants-application",
      "niche.com/colleges/scholarships",
      "fastweb.com",
      "bold.org/scholarships",
      "appily.com/scholarships",
      "bigfuture.collegeboard.org/scholarship-search",
      "unigo.com",
      "petersons.com",
      "scholarships.com",
      "scholarships.gov.in/student-announcements",
    ],
    bootcamp: [
      "springboard.com",
      "codingdojo.com",
      "flatironschool.com",
      "brainstation.io",
      "actualize.co",
      "generalassemb.ly",
      "careerfoundry.com/en/blog/web-development/11-free-coding-bootcamps",
      "thinkful.com",
      "chegg.com/skills/our-programs",
    ],
    "tech fest": [
      "knowafest.com/explore/events",
      "ifp.world",
    ],
    "government programs": [
      "mybharat.gov.in",
      "fitindia.gov.in",
      "nationalsportstalenthunt.com/iFileSAI/showScheme/showSchemePage",
    ],
    conference: [
      "ima-india.org/ima/event-upcoming.php",
    ],
    research: [
      "scholar.google.com",
      "jstor.org",
      "science.gov",
      "nasa.gov",
      "researchgate.net",
      "loc.gov",
      "pmc.ncbi.nlm.nih.gov",
      "iarco.org",
      "bestcolleges.com/blog/best-online-resources-academic-research",
    ],
    "research paper competition": [
      "researchcomp.org",
    ],
    "research funding": [
      "grants.gov/search-grants",
      "oedb.org/ilibrarian/100_places_to_find_funding_your_research",
    ],
    "research collaboration": [
      "theopenscholar.com",
    ],
    workshop: [
      "khojstudios.org/programmes",
      "ifp.world/brand-solutions",
      "the-aiff.com/workshops",
    ],
    community: [
      "meetup.com",
    ],
    competition: [
      "designboom.com/competitions/all",
      "artcontest.in",
      "indiaart.com/khula-aasmaan/international-online-art-contest.asp",
      "hosa.org/competition",
      "societyforscience.org/regeneron-sts",
      "thebrainbee.org",
      "soinc.org",
      "legalbites.in/categories/opportunities/competitions",
      "lawctopus.com/category/opportunities-events/debates",
      "livelaw.in/lawschool/competitions",
    ],
    "ui/ux competition": [
      "designboom.com/competitions/all", // General design competitions
    ],
    institutes: [
      "chefiica.com",
      "iiccm.in",
      "ssca.edu.in",
      "bccm.in",
    ],
    volunteering: [
      "globalhealthvolunteer.org",
      "youthforindia.org",
      "volunteeringindia.com",
      "idealist.org",
      "volunteermatch.org",
    ],
    programs: [
      "fitindia.gov.in/fit-india-school",
      "sportzvillage.com",
    ],
    tournaments: [
        "runningcalendar.in", // General running events
    ],
    trails: [
      "nclindia.in",
      "dlcl.in/registration",
      "t20npl.in/upcoming-cricket-trials-dates-updates",
    ],
    opportunity: [
      "artcontest.in",
      "nhm.gov.in",
      "ayush.gov.in",
      "lawbhoomi.com/category/opportunities",
      "decathlon.in/careers",
      "the-aiff.com/employment",
    ],
    default: [
      "hackathon.com",
      "devpost.com",
      "mlh.io",
      "internshala.com",
      "edx.org",
      "scholarships.com",
      "coursera.org",
      "fastweb.com",
      "volunteeringindia.com",
      "youthforindia.org/application",
      "knowafest.com/explore/events",
      "meetup.com/topics",
    ],
  };